#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'


	require "./lexer"


class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 155)

	# This code will be puts as-is in the Parser class
	def parse(input, show_tokens=true)

		@tokens = Lexer.new.tokenise(innput) # Tokenise the code using our lexer

		puts @tokens.inspect if show_tokens

		do_parse # Kickoff the parsing process

	end

	def next_token

		@tokens.shift

	end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    23,    22,    13,    15,    16,    17,    18,    19,    20,    21,
    13,    23,    22,    13,    15,    16,    17,    18,    19,    20,
    21,    26,    66,    37,    38,    67,    12,    26,    14,    37,
    38,    35,    36,    41,    13,    40,    14,    12,    79,    14,
    23,    22,    26,    15,    16,    17,    18,    19,    20,    21,
    23,    22,    73,    15,    16,    17,    18,    19,    20,    21,
    14,    71,    42,    70,    23,    22,    12,    15,    16,    17,
    18,    19,    20,    21,    23,    22,    12,    15,    16,    17,
    18,    19,    20,    21,    26,    43,    37,    38,    23,    22,
    12,    15,    16,    17,    18,    19,    20,    21,    23,    22,
    12,    15,    16,    17,    18,    19,    20,    21,    71,    78,
    80,    77,    23,    22,    12,    15,    16,    17,    18,    19,
    20,    21,    23,    22,    12,    15,    16,    17,    18,    19,
    20,    21,    45,    69,    24,    26,    23,    22,    12,    15,
    16,    17,    18,    19,    20,    21,    23,    22,    12,    15,
    16,    17,    18,    19,    20,    21,    47,    67,    82,   nil,
    23,    22,    12,    15,    16,    17,    18,    19,    20,    21,
    23,    22,    12,    15,    16,    17,    18,    19,    20,    21,
   nil,   nil,   nil,   nil,    23,    22,    12,    15,    16,    17,
    18,    19,    20,    21,    23,    22,    12,    15,    16,    17,
    18,    19,    20,    21,   nil,   nil,   nil,   nil,    23,    22,
    12,    15,    16,    17,    18,    19,    20,    21,    23,    22,
    12,    15,    16,    17,    18,    19,    20,    21,   nil,   nil,
   nil,   nil,    23,    22,    12,    15,    16,    17,    18,    19,
    20,    21,    23,    22,    12,    15,    16,    17,    18,    19,
    20,    21,   nil,   nil,   nil,   nil,    23,    22,    12,    15,
    16,    17,    18,    19,    20,    21,    23,    22,    12,    15,
    16,    17,    18,    19,    20,    21,   nil,   nil,   nil,   nil,
   nil,    26,    12,    37,    38,    35,    36,    31,    32,    33,
    34,    26,    12,    37,    38,    35,    36,    31,    32,    33,
    34,    29,    30,    28,    27,   nil,   nil,   nil,   nil,    26,
    67,    37,    38,    35,    36,    31,    32,    33,    34,    29,
    30,    28,    27,   nil,   nil,    26,    60,    37,    38,    35,
    36,    31,    32,    33,    34,    29,    30,    28,    27,    26,
   nil,    37,    38,    35,    36,    31,    32,    33,    34,    29,
    30,    28,    27,    26,   nil,    37,    38,    35,    36,    31,
    32,    33,    34,    29,    30,    28,    27,    26,   nil,    37,
    38,    35,    36,    31,    32,    33,    34,    29,    30,    28,
    27,    26,   nil,    37,    38,    35,    36,    31,    32,    33,
    34,    29,    30,    28,    27,    26,   nil,    37,    38,    35,
    36,    31,    32,    33,    34,    29,    30,    28,    27,    26,
   nil,    37,    38,    35,    36,    31,    32,    33,    34,    29,
    30,    28,    26,   nil,    37,    38,    35,    36,    31,    32,
    33,    34,    29,    30,    26,   nil,    37,    38,    35,    36,
    31,    32,    33,    34,    26,   nil,    37,    38,    35,    36,
    26,   nil,    37,    38,    35,    36,    26,   nil,    37,    38,
    35,    36 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    74,    67,    67,    67,    67,    67,    67,    67,    67,    67,
    67,    56,    43,    56,    56,    43,     0,    54,     0,    54,
    54,    54,    54,    20,     2,    20,    74,    67,    74,    67,
    27,    27,    59,    27,    27,    27,    27,    27,    27,    27,
    12,    12,    66,    12,    12,    12,    12,    12,    12,    12,
     2,    61,    21,    61,    69,    69,    27,    69,    69,    69,
    69,    69,    69,    69,    40,    40,    12,    40,    40,    40,
    40,    40,    40,    40,    57,    22,    57,    57,    23,    23,
    69,    23,    23,    23,    23,    23,    23,    23,    42,    42,
    40,    42,    42,    42,    42,    42,    42,    42,    75,    72,
    75,    72,    25,    25,    23,    25,    25,    25,    25,    25,
    25,    25,    41,    41,    42,    41,    41,    41,    41,    41,
    41,    41,    24,    47,     1,    58,    71,    71,    25,    71,
    71,    71,    71,    71,    71,    71,    28,    28,    41,    28,
    28,    28,    28,    28,    28,    28,    26,    77,    78,   nil,
    29,    29,    71,    29,    29,    29,    29,    29,    29,    29,
    30,    30,    28,    30,    30,    30,    30,    30,    30,    30,
   nil,   nil,   nil,   nil,    31,    31,    29,    31,    31,    31,
    31,    31,    31,    31,    32,    32,    30,    32,    32,    32,
    32,    32,    32,    32,   nil,   nil,   nil,   nil,    33,    33,
    31,    33,    33,    33,    33,    33,    33,    33,    34,    34,
    32,    34,    34,    34,    34,    34,    34,    34,   nil,   nil,
   nil,   nil,    35,    35,    33,    35,    35,    35,    35,    35,
    35,    35,    36,    36,    34,    36,    36,    36,    36,    36,
    36,    36,   nil,   nil,   nil,   nil,    37,    37,    35,    37,
    37,    37,    37,    37,    37,    37,    38,    38,    36,    38,
    38,    38,    38,    38,    38,    38,   nil,   nil,   nil,   nil,
   nil,    50,    37,    50,    50,    50,    50,    50,    50,    50,
    50,    44,    38,    44,    44,    44,    44,    44,    44,    44,
    44,    44,    44,    44,    44,   nil,   nil,   nil,   nil,    39,
    44,    39,    39,    39,    39,    39,    39,    39,    39,    39,
    39,    39,    39,   nil,   nil,    76,    39,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,     3,
   nil,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,    63,   nil,    63,    63,    63,    63,    63,
    63,    63,    63,    63,    63,    63,    63,    64,   nil,    64,
    64,    64,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    46,   nil,    46,    46,    46,    46,    46,    46,    46,
    46,    46,    46,    46,    46,    62,   nil,    62,    62,    62,
    62,    62,    62,    62,    62,    62,    62,    62,    62,    48,
   nil,    48,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,    49,   nil,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    51,   nil,    51,    51,    51,    51,
    51,    51,    51,    51,    53,   nil,    53,    53,    53,    53,
    52,   nil,    52,    52,    52,    52,    55,   nil,    55,    55,
    55,    55 ]

racc_action_pointer = [
    -2,   134,    30,   327,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    48,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     7,    36,    75,    86,   132,   110,   146,    38,   144,   158,
   168,   182,   192,   206,   216,   230,   240,   254,   264,   297,
    72,   120,    96,    -6,   279,   nil,   369,   105,   397,   410,
   269,   422,   438,   432,    15,   444,     9,    72,   123,    30,
   nil,    34,   383,   341,   355,   nil,    42,     9,   nil,    62,
   nil,   134,    82,   nil,     6,    81,   313,   126,   148,   nil,
   nil,   nil,   nil ]

racc_action_default = [
    -1,   -51,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -51,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -41,   -51,   -51,   -51,    -5,   -51,   -51,   -51,   -51,
   -51,   -51,   -51,   -51,   -51,   -51,   -51,   -51,   -51,   -51,
   -26,   -51,   -51,   -51,   -51,    83,    -4,   -24,   -29,   -30,
   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,   -40,
   -14,   -51,   -27,   -42,   -43,   -44,   -46,   -51,   -49,   -26,
   -23,   -51,   -51,   -47,   -51,   -51,   -28,   -51,   -51,   -50,
   -25,   -45,   -48 ]

racc_goto_table = [
    25,     2,    39,    65,    68,    61,     1,    72,   nil,   nil,
   nil,   nil,   nil,    44,   nil,    46,   nil,    48,    49,    50,
    51,    52,    53,    54,    55,    56,    57,    58,    59,   nil,
    62,    63,    64,   nil,    75,   nil,   nil,    81,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    62,
   nil,    76,   nil,   nil,   nil,   nil,   nil,   nil,    74,   nil,
   nil,   nil,    25 ]

racc_goto_check = [
     4,     2,     3,    13,    13,    12,     1,    14,   nil,   nil,
   nil,   nil,   nil,     3,   nil,     3,   nil,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,   nil,
     3,     3,     3,   nil,    12,   nil,   nil,    13,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     6,     1,   -10,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -35,   -40,   -59 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 34, :_reduce_none,
  1, 34, :_reduce_none,
  1, 35, :_reduce_none,
  3, 35, :_reduce_none,
  2, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 36, :_reduce_none,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  1, 39, :_reduce_none,
  4, 39, :_reduce_none,
  3, 39, :_reduce_none,
  6, 39, :_reduce_none,
  0, 45, :_reduce_none,
  1, 45, :_reduce_none,
  3, 45, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  3, 40, :_reduce_none,
  1, 41, :_reduce_none,
  3, 42, :_reduce_none,
  3, 42, :_reduce_none,
  3, 43, :_reduce_none,
  6, 43, :_reduce_none,
  0, 47, :_reduce_none,
  1, 47, :_reduce_none,
  3, 47, :_reduce_none,
  3, 44, :_reduce_none,
  3, 46, :_reduce_none ]

racc_reduce_n = 51

racc_shift_n = 83

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :FUNC => 3,
  :NEWLINE => 4,
  :NUMBER => 5,
  :STRING => 6,
  :TRUE => 7,
  :FALSE => 8,
  :NULL => 9,
  :IDENTIFIER => 10,
  :CONSTANT => 11,
  "." => 12,
  "!" => 13,
  "*" => 14,
  "/" => 15,
  "+" => 16,
  "-" => 17,
  ">" => 18,
  ">=" => 19,
  "<" => 20,
  "<=" => 21,
  "==" => 22,
  "!=" => 23,
  "&&" => 24,
  "||" => 25,
  "=" => 26,
  "," => 27,
  "(" => 28,
  ")" => 29,
  ";" => 30,
  "{" => 31,
  "}" => 32 }

racc_nt_base = 33

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "FUNC",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NULL",
  "IDENTIFIER",
  "CONSTANT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Func",
  "If",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
